import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import  Footer  from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from 'react-hot-toast';
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import Head from "next/head";

const poppins = Poppins({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Globit",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <html lang="en">
      <Head>
        <link rel="canonical" href="https://globit.me" />
      </Head>
      <body className={poppins.className}>
        <SessionProvider session={session}>
          <Navbar />
          <div>{children}</div>
        </SessionProvider>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
