import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import  Footer  from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from 'react-hot-toast';
import NavSession from "@/components/navbar/NavSession";

const poppins = Poppins({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Globit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavSession />
        <div>{children}</div>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
